no autoremove

diff --git a/package/contents/scripts/upgradepackages b/package/contents/scripts/upgradepackages
--- a/package/contents/scripts/upgradepackages
+++ b/package/contents/scripts/upgradepackages
@@ -43,18 +43,18 @@ fi
 
 # Prompt to autoremove packages if we have some.
 # https://askubuntu.com/questions/652363/how-can-i-get-a-list-with-the-packages-selected-by-apt-get-autoremove
-autoremovePackages=`apt --dry-run autoremove 2>/dev/null | grep -Po 'Remv \K[^ ]+'`
-if [[ ! -z "$autoremovePackages" ]]; then
-    echo ""
-    echoCommand "sudo apt autoremove"
-    notify-send --icon="update-none" "Auto-Remove Packages" "Need to cleanup unused packages."
-    sudo apt autoremove
-    result="$?"
-    if [ $result != 0 ]; then
-        notify-send --icon="dialog-error" "Could Not Auto-Remove Packages" "Error while attempting to remove auto-removeable packages."
-        exit $result
-    fi
-fi
+# autoremovePackages=`apt --dry-run autoremove 2>/dev/null | grep -Po 'Remv \K[^ ]+'`
+# if [[ ! -z "$autoremovePackages" ]]; then
+#    echo ""
+#    echoCommand "sudo apt autoremove"
+#    notify-send --icon="update-none" "Auto-Remove Packages" "Need to cleanup unused packages."
+#    sudo apt autoremove
+#    result="$?"
+#    if [ $result != 0 ]; then
+#        notify-send --icon="dialog-error" "Could Not Auto-Remove Packages" "Error while attempting to remove auto-removeable packages."
+#        exit $result
+#    fi
+#fi
 
 
 # Bell when done.
